dist: trusty
sudo: false

language: c
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - rake
      - psmisc
      - bison
      - git
      - gperf
      - libfuse-dev

before_script:
  - cp -fp .travis_build_config.rb build_config.rb
script:
  - rake test
