dist: trusty
sudo: false

language: c
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - rake
      - psmisc
      - bison
      - git
      - gperf
      - libfuse-dev

script:
  - rake test
